#name of file
name: Variable-obj

on:
# event_trigger
  workflow_dispatch:
    inputs:
      name:
        description: Retrieving Github context and variable
        required: true
        type: string

# job to execute
jobs: 
  job-1:
    runs-on: ubuntu-latest  
    #job to capture GITHUBcontext objects
    steps:
    - name: Github variable details
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run:  |
        echo  "printing github context"
        echo ${{ GITHUB_CONTEXT}}
        
